Fix sendEmail undefined error in Firebase Functions
Added missing sendEmail function implementation that queues emails
via Firestore mail collection for processing by Firebase mail extension.

Fixes ESLint errors:
- functions/index.js:472:17 error 'sendEmail' is not defined
- functions/index.js:504:17 error 'sendEmail' is not defined